name: Demo

on:
  push:
    branches:
      - main
    paths:
      - '**.html'
      - '**.yml'

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: this is print statement
        run: echo "hello everybody"
  listfiles:
    needs:
      - code # this says only run this job after completion of code
    runs-on: ubuntu-latest
    steps:
      - name: list all files in root folder
        run: ls -l /
    
